### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by dajocarter** [humanmade/react-wp-scripts#43]
After generating the app using the npx command, I can run `npm run build` just fine but `npm start` does not work.

I get 
```
Error: Cannot find module '../scripts/start'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/Users/dajocarter/Sites/bedrock/app/public/web/app/plugins/product-plugin/app/node_modules/.bin/react-wp-scripts:26:21)
```

**Comment by dajocarter** [comment]
Had to reinstall `node_modules`
